trabajopython/contabilidad/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *
from producto import views

urlpatterns = [

    # traspaso fondos
    url(r'^contabilidad/traspaso/listar', TraspasoDineroList.as_view(), name='traspaso_list'),
    url(r'^contabilidad/traspaso/crear', TraspasoDineroCreate.as_view(), name='traspaso_crear'),
    url(r'^contabilidad/traspaso/editar/(?P<pk>\d+)$', TraspasoDineroUpdate.as_view(), name='traspaso_editar'),
    url(r'^contabilidad/traspaso/eliminar/(?P<pk>\d+)$', TraspasoDineroDelete.as_view(), name='traspaso_eliminar'),

    # cuentas
    #url(r'^contabilidad/listar/cuenta', CuentaList.as_view(), name='cuenta_list'),

    #reportes
    url(r'^contabilidad/reporteContabilidad/$', ReporteContabilidadPDF.as_view(), name='reporteContabilidad'),
    url(r'^contabilidad/reporteFondos/$', ReporteFondosPDF.as_view(), name='reporteFondos'),
    # cuentas
    url(r'^contabilidad/cuenta/listar$', CuentaList.as_view(), name='cuenta_list'),
    url(r'^contabilidad/cuenta/crear$', CuentaCreate.as_view(), name='cuenta_crear'),
    url(r'^contabilidad/cuenta/editar/(?P<pk>\d+)/$', CuentaUpdate.as_view(), name='cuenta_editar'),
    url(r'^contabilidad/cuenta/eliminar/(?P<pk>\d+)/$', CuentaDelete.as_view(), name='cuenta_eliminar'),
]

trabajopython/home/urls.py
from django.conf.urls import url
from .views import HomeTemplateView


urlpatterns = [
    url(r'^$', HomeTemplateView.as_view(), name='index'),
]

trabajopython/trabajopython/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('home.urls', namespace='home')),    

    #URL de producto
    url(r'^', include('producto.urls', namespace="producto")),

    #URL de adquisiciones
    url(r'^', include('adquisiciones.urls', namespace="adquisiciones")),

    #URL de proveedor
    url(r'^', include('proveedor.urls', namespace="proveedor")),
    
    #URL de organizacion
    url(r'^', include('organizacion.urls', namespace="organizacion")),

    #URL de inventario
    url(r'^', include('inventario.urls', namespace="inventario")),

    #URLS de contabilidad
    url(r'^', include('contabilidad.urls', namespace="cuenta")),
    url(r'^', include('contabilidad.urls', namespace="traspaso")),
        url(r'^', include('contabilidad.urls', namespace="contabilidad")),

    #URL de bodega
    url(r'^', include('bodega.urls', namespace="bodega")),
    url(r'^', include('bodega.urls', namespace="ubicacion")),
]

trabajopython/contabilidad/models.py
from django.db import models

# Create your models here.



class Cuenta(models.Model):
    tipo_cuenta = models.CharField(verbose_name='Tipo de cuenta', max_length=100,
                                   choices= ( ('1.- Computacion','Computacion'),('2.- Vehiculos','Vehiculos'),('3.- Inmuebles','Inmuebles')), unique = True)
    fondos_actuales = models.IntegerField(verbose_name='Fondos actuales')
    fondos_minimos = models.IntegerField(verbose_name='Fondos minimos')

    def __str__(self):
        return self.tipo_cuenta

    class Meta:
        verbose_name = "Cuenta"


class TraspasoDinero(models.Model):
    cuenta_origen = models.ForeignKey(Cuenta)
    cuenta_destino = models.CharField(verbose_name='Tipo de cuenta', max_length=100,
                                   choices= ( ('1','Computacion'),('2','Vehiculos'),('3','Inmuebles')))
    fecha = models.DateField(auto_now=False, auto_now_add=False)
    monto = models.IntegerField()

    def __int__(self):
        return self.id
    class Meta:
        verbose_name = "Traspaso de dinero"

trabajopython/contabilidad/forms.py
from django import forms

from .models import TraspasoDinero
from .models import Cuenta


class TraspasoDineroForm(forms.ModelForm):
    class Meta:
        model = TraspasoDinero

        fields = [
            'cuenta_origen',
            'cuenta_destino',
            'fecha',
            'monto',
        ]

        labels = {
            'cuenta_origen': 'Cuenta de origen',
            'cuenta_destino': 'cuenta de destino',
            'fecha': 'Fecha',
            'monto': 'Monto',
        }

        widgets = {
            'cuenta_origen': forms.Select(attrs={'class': 'form-control'}),
            'cuenta_destino': forms.Select(attrs={'class': 'form-control'}),
            'fecha': forms.SelectDateWidget(),
            'monto': forms.NumberInput(attrs={'class': 'form-control'}),
        }
class CuentaForm(forms.ModelForm):
    class Meta:
        model = Cuenta

        fields = [
            'tipo_cuenta',
            'fondos_actuales',
            'fondos_minimos',
        ]
        labels = {
            'tipo_cuenta': 'Tipo de cuenta',
            'fondos_actuales': 'Fondos actuales',
            'fondos_minimos': 'Fondos minimos',
        }
        widgets = {
            'tipo_cuenta': forms.Select(attrs={'class': 'form-control'}),
            'fondos_actuales': forms.NumberInput(attrs={'class': 'form-control'}),
            'fondos_minimos': forms.NumberInput(attrs={'class': 'form-control'}),
        }

trabajopython/contabilidad/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import *
from .models import *
from .urls import *
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Table, TableStyle, Image
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from django.views.generic import View
from django.http import HttpResponse
from django.db.models import Count
# Create your views here.

class TraspasoDineroList(ListView):
    model = TraspasoDinero
    template_name = 'contabilidad/traspaso_list.html'

class TraspasoDineroCreate(CreateView):
    model = TraspasoDinero
    form_class = TraspasoDineroForm
    template_name = 'contabilidad/traspaso_create.html'
    success_url = reverse_lazy('traspaso:traspaso_list')
    success_message = 'Traspaso aprovado'

class TraspasoDineroUpdate(UpdateView):
    model = TraspasoDinero
    form_class = TraspasoDineroForm
    template_name = 'contabilidad/traspaso_update.html'
    success_url = reverse_lazy('traspaso:traspaso_list')


class TraspasoDineroDelete(DeleteView):
    model = TraspasoDinero
    template_name = 'contabilidad/traspaso_delete.html'
    success_url = reverse_lazy('traspaso:traspaso_list')

class CuentaList(ListView):
    model = Cuenta
    template_name = 'cuenta/cuenta_list.html'

class CuentaCreate(CreateView):
    model = Cuenta
    form_class = CuentaForm
    template_name = 'cuenta/cuenta_create.html'
    success_url = reverse_lazy('cuenta:cuenta_list')
    success_message = 'Cuenta creada'

class CuentaUpdate(UpdateView):
    model = Cuenta
    form_class = CuentaForm
    template_name = 'cuenta/cuenta_update.html'
    success_url = reverse_lazy('cuenta:cuenta_list')


class CuentaDelete(DeleteView):
    model = Cuenta
    template_name = 'cuenta/cuenta_delete.html'
    success_url = reverse_lazy('cuenta:cuenta_list')


class ReporteContabilidadPDF(View):
    def cabecera(self,pdf):
        #archivo_imagen = settings.STATIC_ROOT+'/img/escudo.png'
        #pdf.drawImage(archivo_imagen, 50, 740, 120, 90, preserveAspectRatio=True)
        pdf.setFont("Helvetica", 16)
        pdf.drawString(220, 790, u"Contabilidad")
        pdf.setFont("Helvetica", 14)
        pdf.drawString(200, 770, u"Reporte de traspasos")

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='application/pdf')
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        self.cabecera(pdf)
        y = 600
        self.tabla(pdf, y)
        pdf.showPage()
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

    def tabla(self, pdf, y):
        encabezados = ('Cuenta Origen', 'Cuenta Destino', 'Fecha', 'Monto')
        detalles = [(con.cuenta_origen.tipo_cuenta, con.cuenta_destino, con.fecha, con.monto)for con in TraspasoDinero.objects.all()]
        detalle_orden = Table([encabezados] + detalles, colWidths=[4 * cm, 3 * cm, 3 * cm, 3 * cm])
        detalle_orden.setStyle(TableStyle(
        [
            ('ALIGN', (0,0),(3,0), 'CENTER'),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ]
        ))
        detalle_orden.wrapOn(pdf, 800, 600)
        detalle_orden.drawOn(pdf, 60, y)
    template_name = 'contabilidad/reporteContabilidad.html'

class ReporteFondosPDF(View):
    def cabecera(self,pdf):
        #archivo_imagen = settings.STATIC_ROOT+'/img/escudo.png'
        #pdf.drawImage(archivo_imagen, 50, 740, 120, 90, preserveAspectRatio=True)
        pdf.setFont("Helvetica", 16)
        pdf.drawString(245, 790, u"Contabilidad")
        pdf.setFont("Helvetica", 14)
        pdf.drawString(200, 770, u"Reporte de Fondos")

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='application/pdf')
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        self.cabecera(pdf)
        y = 600
        self.tabla(pdf, y)
        pdf.showPage()
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

    def tabla(self, pdf, y):
        encabezados = ('Cuenta Origen','Monto')
        #detalles= [ (c, TraspasoDinero.objects.filter( monto=c.id ).count()) for c in TraspasoDinero.objects.all() ]
        detalles = [(TraspasoDinero.cuenta_origen, TraspasoDinero.monto)for TraspasoDinero in TraspasoDinero.objects.all()]
        detalle_orden = Table([encabezados] + detalles, colWidths=[3 * cm, 3 * cm])
        detalle_orden.setStyle(TableStyle(
            [
                ('ALIGN', (0, 0), (1, 0), 'CENTER'),
                ('GRID', (0, 0), (8, -1), 0.5, colors.darkgrey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('FONTSIZE', (0, 0), (-1, -1), 8)

            ]
        ))
        detalle_orden.wrapOn(pdf, 800, 600)
        detalle_orden.drawOn(pdf, 60, y)

    template_name = 'contabilidad/reporteFondos.html'

trabajopython/contabilidad/templates/contabilidad/reporteContabilidad.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Contabilidad | Reporte contabilidad</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}
	<div class="form-group">
		<div class="row">
			<div class="col-lg-1">
				<a href="{% url 'contabilidad:reporteContabilidad' %}" class="btn btn-info btn-block">
					<span class=""></span>
				</a>
			</div>
		</div>
	</div>
</html>
{% endblock %}

trabajopython/contabilidad/templates/contabilidad/reporteFondos.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Contabilidad | Reporte Fondos</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}
	<div class="form-group">
		<div class="row">
			<div class="col-lg-1">
				<a href="{% url 'contabilidad:reporteFondos' %}" class="btn btn-info btn-block">
					<span class=""></span>
				</a>
			</div>
		</div>
	</div>
</html>
{% endblock %}

trabajopython/contabilidad/templates/contabilidad/traspaso_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Contabilidad</title>
</head>
<body>
    {% extends 'adminlte/base.html'%}

    {%block content%}
    <div class="col-sm-12">
        <h1>Traspasos de fondos</h1>
        <hr>
        <form method="POST" action="">
            {% csrf_token%}
            {{form.as_p}}
            <input type='submit' class="btn btn-primary" value='Guardar Registro'>
        </form>
    </div>
</body>
</html>
{%endblock%}

trabajopython/contabilidad/templates/contabilidad/traspaso_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | Eliminar Traspaso</title>
  </head>
{% extends 'adminlte/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el traspaso "{{ object.id }}" ?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'traspaso:traspaso_list' %}">Cancelar</a>

</form>
</html>
{% endblock %}

trabajopython/contabilidad/templates/contabilidad/traspaso_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Listar Traspasos</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE TRASPASOS</h1>
    <a class="btn btn-primary" href="{% url 'traspaso:traspaso_crear' %}"><i class="fa fa-plus-square" aria-hidden="true"></i> Agregar</a>
    <a class="btn btn-primary" href="{% url 'traspaso:reporteFondos' %}"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Reporte traspasos</a>

    <!--<a class="btn btn-primary" href="{% url 'traspaso:reporte_fondos_pdf' %}"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Reporte fondos actuales</a>-->
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Codigo</td>
				<td>Cuenta origen</td>
				<td>Cuenta destino</td>
				<td>Fecha</td>
				<td>Monto</td>
			</tr>
		</thead>
		<tbody>
			{% for traspaso_list in object_list %}
			<tr>
				<td>{{traspaso_list.id}}</td>
				<td>{{traspaso_list.cuenta_origen.tipo_cuenta}}</td>
				<td>{{traspaso_list.cuenta_destino}}</td>
				<td>{{traspaso_list.fecha}}</td>
				<td>{{traspaso_list.monto}}</td>
        <td style="border :1px solid transparent ">
				  <a class="btn btn-primary" href="{% url 'traspaso:traspaso_editar' traspaso_list.id %}"><i class="ion-edit"></i> Editar</a>
          <a class="btn btn-danger" href="{% url 'traspaso:traspaso_eliminar' traspaso_list.id %}"> <i class="ion-android-delete"></i> Eliminar</a>
          <a class="btn btn-success" href="{% url 'contabilidad:reporteContabilidad' %}"> <i class="ion-android-delete"></i> Mostrar reporte contabilidad</a>
        </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay registro de traspasos</h1>
	<hr>
	<td>
		<a class="btn btn-primary" href="{% url 'traspaso:traspaso_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>
		<a class="btn btn-success" href="{% url 'contabilidad:reporteContabilidad' %}"> <i class="ion-android-delete"></i> Mostrar reporte contabilidad</a>
	</td>
	{% endif %}
</div>
</div>
 </html>
{% endblock %}

trabajopython/contabilidad/templates/contabilidad/traspaso_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | TRASPASO-Editar</title>
  </head>
{% extends 'adminlte/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR TRASPASO</h1>
          <hr>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
            </form>
      </div>
  </div>
  <br>
</html>
{%endblock%}