trabajopython/bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *
from bodega import views

urlpatterns = [
    #bodega
    url(r'^bodega/crear/bodega$', BodegaCreate.as_view(), name='bodega_crear'),
    url(r'^bodega/listar/bodega$', BodegaList.as_view(), name='bodega_listar'),
    url(r'^bodega/editar/bodega/(?P<pk>\d+)/$', BodegaUpdate.as_view(), name='bodega_editar'),
    url(r'^bodega/eliminar/bodega/(?P<pk>\d+)/$', BodegaDelete.as_view(), name='bodega_eliminar'),
    #ubicacion
    url(r'^ubicacion/crear/ubicacion$', UbicacionCreate.as_view(), name='ubicacion_crear'),
    url(r'^ubicacion/listar/ubicacion$', UbicacionList.as_view(), name='ubicacion_listar'),
    url(r'^ubicacion/editar/ubicacion/(?P<pk>\d+)/$', UbicacionUpdate.as_view(), name='ubicacion_editar'),
    url(r'^ubicacion/eliminar/ubicacion/(?P<pk>\d+)/$', UbicacionDelete.as_view(), name='ubicacion_eliminar'),

    url(r'^bodega/reporte$', Reporte.as_view(), name='reporte'),
]

trabajopython/home/urls.py
from django.conf.urls import url
from .views import HomeTemplateView


urlpatterns = [
    url(r'^$', HomeTemplateView.as_view(), name='index'),
]

trabajopython/inventario/urls.py
from django.conf.urls import url
from .views import *
from django.contrib import admin

urlpatterns = [
    url(r'^inventario/listar/inventario', ListInventario.as_view(), name='listar_inventario'),
    url(r'^inventario/crear/inventario', CreateInventario.as_view(), name='crear_inventario'),
    url(r'^inventario/editar/inventario/(?P<pk>\d+)$', UpdateInventario.as_view(), name='editar_inventario'),
    url(r'^inventario/eliminar/inventario/(?P<pk>\d+)$', DeleteInventario.as_view(), name='eliminar_inventario'),
    url(r'^inventario/reporte$', ReporteInventario.as_view(), name='reporte_inventario'),
]

trabajopython/producto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *
from producto import views


urlpatterns = [
	#producto
	url(r'^producto/listar/producto$', ProductoList.as_view(), name='producto_listar'),
    url(r'^producto/crear/producto$', ProductoCreate.as_view(), name='producto_crear'),
    url(r'^producto/editar/producto/(?P<pk>\d+)/$', ProductoUpdate.as_view(), name='producto_editar'),
    url(r'^producto/eliminar/producto/(?P<pk>\d+)/$', ProductoDelete.as_view(), name='producto_eliminar'),
]

trabajopython/proveedor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *
from producto import views


urlpatterns = [
	#producto
	url(r'^proveedor/listar/proveedor$', ProveedorList.as_view(), name='proveedor_listar'),
    url(r'^proveedor/crear/proveedor$', ProveedorCreate.as_view(), name='proveedor_crear'),
    url(r'^proveedor/editar/proveedor/(?P<pk>\d+)/$', ProveedorUpdate.as_view(), name='proveedor_editar'),
    url(r'^proveedor/eliminar/proveedor/(?P<pk>\d+)/$', ProveedorDelete.as_view(), name='proveedor_eliminar'),
]

trabajopython/trabajopython/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('home.urls', namespace='home')),    

    #URL de producto
    url(r'^', include('producto.urls', namespace="producto")),

    #URL de adquisiciones
    url(r'^', include('adquisiciones.urls', namespace="adquisiciones")),

    #URL de proveedor
    url(r'^', include('proveedor.urls', namespace="proveedor")),
    
    #URL de organizacion
    url(r'^', include('organizacion.urls', namespace="organizacion")),

    #URL de inventario
    url(r'^', include('inventario.urls', namespace="inventario")),

    #URLS de contabilidad
    url(r'^', include('contabilidad.urls', namespace="cuenta")),
    url(r'^', include('contabilidad.urls', namespace="traspaso")),
        url(r'^', include('contabilidad.urls', namespace="contabilidad")),

    #URL de bodega
    url(r'^', include('bodega.urls', namespace="bodega")),
    url(r'^', include('bodega.urls', namespace="ubicacion")),
]

trabajopython/templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

trabajopython/templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<b>A</b>LTE{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<b>Admin</b>LTE{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

trabajopython/templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}SISTEMA DE NOSEQUE{% endblock %}</li>

            {% block nav_links %}
                <!-- <li>
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Example link</span>
                    </a>
                </li> -->
                <li>
                    <a href="{% url 'home:index' %}">
                        <i class="fa fa-dashboard"></i><span>Inicio</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Producto</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'producto:producto_listar' %}">
                                <i class="fa fa-user"></i> Listar
                            </a>
                            <a href="{% url 'producto:producto_crear' %}">
                                <i class="fa fa-user"></i> Registrar
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Adquisiciones</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'adquisiciones:ordencompra_listar' %}">
                                <i class="fa fa-user"></i> Listar Orden de Compra
                            </a>
                            <a href="{% url 'adquisiciones:ordencompra_crear' %}">
                                <i class="fa fa-user"></i> Registrar Orden de Compra
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'adquisiciones:factura_listar' %}">
                                <i class="fa fa-user"></i> Listar Factura
                            </a>
                            <a href="{% url 'adquisiciones:factura_crear' %}">
                                <i class="fa fa-user"></i> Registrar Factura
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Contabilidad</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'cuenta:cuenta_list' %}">
                                <i class="fa fa-user"></i> Listar Cuentas
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'cuenta:cuenta_crear' %}">
                                <i class="fa fa-user"></i> Crear Cuentas
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'traspaso:traspaso_list' %}">
                                <i class="fa fa-user"></i> Listar traspasos
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'traspaso:traspaso_crear' %}">
                                <i class="fa fa-user"></i> Crear traspaso
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Proveedor</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'proveedor:proveedor_listar' %}">
                                <i class="fa fa-user"></i> Listar
                            </a>
                            <a href="{% url 'proveedor:proveedor_crear' %}">
                                <i class="fa fa-user"></i> Registrar
                            </a>
                        </li>
                    </ul>
                    <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Inventario</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'inventario:crear_inventario' %}">
                                <i class="fa fa-user"></i> Crear Inventario
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'inventario:listar_inventario' %}">
                                <i class="fa fa-user"></i> Listar Inventario
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Organizacion</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'organizacion:crear_organizacion' %}">
                                <i class="fa fa-user"></i> Crear Organizacion
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'organizacion:listar_organizacion' %}">
                                <i class="fa fa-user"></i> Listar Organizacion
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'organizacion:crear_direccion' %}">
                                <i class="fa fa-user"></i> Crear Direccion
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'organizacion:listar_direccion' %}">
                                <i class="fa fa-user"></i> Listar Direccion
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'organizacion:crear_departamento' %}">
                                <i class="fa fa-user"></i> Crear Departamento
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'organizacion:listar_departamento' %}">
                                <i class="fa fa-user"></i> Listar Departamento
                            </a>
                        </li>
                    </ul>
                </li>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-th"></i> <span>Bodega</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'bodega:bodega_crear' %}">
                                <i class="fa fa-user"></i> Crear Bodega
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'bodega:bodega_listar' %}">
                                <i class="fa fa-user"></i> Listar Bodega
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'bodega:ubicacion_crear' %}">
                                <i class="fa fa-user"></i> Crear Ubicacion
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'bodega:ubicacion_listar' %}">
                                <i class="fa fa-user"></i> Listar Ubicacion
                            </a>
                        </li>
                    </ul>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'bodega:reporte' %}">
                                <i class="fa fa-user"></i> Reporte de productos en bodega
                            </a>
                        </li>
                    </ul>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>

trabajopython/templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

trabajopython/templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

trabajopython/templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "jquery/dist/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %} "></script>
<script src="{% static "admin-lte/dist/js/app.min.js" %}"></script>
{% endblock %}

trabajopython/templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/AdminLTE.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/skins/_all-skins.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "icheck/skins/square/blue.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "conflicts/conflicts.css" %}">
{% endblock %}