trabajopython/adquisiciones/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *
from producto import views


urlpatterns = [
	#OrdenCompra
	url(r'^adquisiciones/listar/ordencompra$', OrdenCompraList.as_view(), name='ordencompra_listar'),
    url(r'^adquisiciones/crear/ordencompra$', OrdenCompraCreate.as_view(), name='ordencompra_crear'),
    url(r'^adquisiciones/editar/ordencompra/(?P<pk>\d+)/$', OrdenCompraUpdate.as_view(), name='ordencompra_editar'),
    url(r'^adquisiciones/eliminar/ordencompra/(?P<pk>\d+)/$', OrdenCompraDelete.as_view(), name='ordencompra_eliminar'),
    url(r'^adquisiciones/reporte$', Reporte.as_view(), name='reporte'),
    #Factura
    url(r'^adquisiciones/listar/factura$', FacturaList.as_view(), name='factura_listar'),
    url(r'^adquisiciones/crear/factura$', FacturaCreate.as_view(), name='factura_crear'),
    url(r'^adquisiciones/editar/factura/(?P<pk>\d+)/$', FacturaUpdate.as_view(), name='factura_editar'),
    url(r'^adquisiciones/eliminar/factura/(?P<pk>\d+)/$', FacturaDelete.as_view(), name='factura_eliminar'),
]

trabajopython/home/urls.py
from django.conf.urls import url
from .views import HomeTemplateView


urlpatterns = [
    url(r'^$', HomeTemplateView.as_view(), name='index'),
]

trabajopython/trabajopython/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('home.urls', namespace='home')),    

    #URL de producto
    url(r'^', include('producto.urls', namespace="producto")),

    #URL de adquisiciones
    url(r'^', include('adquisiciones.urls', namespace="adquisiciones")),

    #URL de proveedor
    url(r'^', include('proveedor.urls', namespace="proveedor")),
    
    #URL de organizacion
    url(r'^', include('organizacion.urls', namespace="organizacion")),

    #URL de inventario
    url(r'^', include('inventario.urls', namespace="inventario")),

    #URLS de contabilidad
    url(r'^', include('contabilidad.urls', namespace="cuenta")),
    url(r'^', include('contabilidad.urls', namespace="traspaso")),
        url(r'^', include('contabilidad.urls', namespace="contabilidad")),

    #URL de bodega
    url(r'^', include('bodega.urls', namespace="bodega")),
    url(r'^', include('bodega.urls', namespace="ubicacion")),
]

trabajopython/adquisiciones/models.py
from django.db import models
from producto.models import Producto
from proveedor.models import Proveedor
from organizacion.models import Departamento
#from contabilidad.models import Cuenta

# Create your models here.

class OrdenCompra(models.Model):
    producto = models.ForeignKey(Producto, default="")
    total = models.IntegerField(blank=False, null=False, verbose_name="Precio")
    estado = models.CharField(max_length=20, choices=(('1', 'Aceptado'), ('0', 'Rechazado'), ('2', 'En Proceso')), verbose_name="Estado")
    observacion = models.CharField(max_length=200, verbose_name="Observacion")
    departamento = models.ForeignKey(Departamento)
    fecha = models.DateField(auto_now=False, auto_now_add=False)
    #cuenta=models.ForeignKey(Cuenta)

    def __int__(self):
        return self.id

    class Meta:
        verbose_name="Orden de Compra"

class Factura(models.Model):
    producto = models.ForeignKey(Producto)
    proveedor = models.ForeignKey(Proveedor)
    fecha = models.DateField(auto_now=False, auto_now_add=False, verbose_name="Fecha")
    total = models.IntegerField(blank=False, null=False, verbose_name="Total")

    def __int__(self):
        return self.id

    class Meta:
        verbose_name="Factura"

trabajopython/adquisiciones/forms.py
from django import forms
from .models import *
from datetimewidget.widgets import DateWidget

class OrdenCompraForm(forms.ModelForm):

	class Meta:
		model = OrdenCompra

		fields = [
			'producto',
			'total',
			'estado',
			'observacion',
			'departamento',
			'fecha',
		]
		labels = {
			'producto': 'Producto',
			'total': 'Total',
			'estado': 'Estado',
			'observacion': 'Observacion',
			'departamento': 'Departamento',
			'fecha': 'Fecha',
		}
		widgets = {
			'producto': forms.Select(attrs={'class': 'form-control'}),
			'total': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese total'}),
			'estado': forms.Select(attrs={'class': 'form-control'}),
			'observacion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ingrese observacion', 'rows': 3}),
			'departamento': forms.Select(attrs={'class': 'form-control'}),
			'fecha': DateWidget(attrs={'id': "fecha"}, usel10n=True, bootstrap_version=3),
		}

class FacturaForm(forms.ModelForm):

	class Meta:
		model = Factura

		fields = [
			'producto',
			'proveedor',
			'fecha',
			'total',
			
		]
		labels = {
			'producto': 'Producto',
			'proveedor': 'Proveedor',
			'fecha': 'Fecha',
			'total': 'Total',
		}
		widgets = {
			'producto': forms.Select(attrs={'class': 'form-control'}),			
			'proveedor': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Ingrese proveedor'}),
			'fecha': DateWidget(attrs={'id': "fecha"}, usel10n=True, bootstrap_version=3),
			'total': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese total'}),
		}

trabajopython/adquisiciones/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import *
from .forms import *
from .models import *
from django.views.generic import View

from reportlab.platypus import TableStyle, Table, Spacer
from reportlab.lib import colors
from reportlab.lib.units import cm
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, landscape
from django.http import HttpResponse
# Create your views here.

class OrdenCompraList(ListView):
    model = OrdenCompra
    template_name = 'adquisiciones/ordencompra_list.html'


class OrdenCompraCreate(CreateView):
    model = OrdenCompra
    form_class = OrdenCompraForm
    template_name = 'adquisiciones/ordencompra_create.html'
    success_url = reverse_lazy('adquisiciones:ordencompra_listar')


class OrdenCompraUpdate(UpdateView):
    model = OrdenCompra
    form_class = OrdenCompraForm
    template_name = 'adquisiciones/ordencompra_update.html'
    success_url = reverse_lazy('adquisiciones:ordencompra_listar')


class OrdenCompraDelete(DeleteView):
    model = OrdenCompra
    template_name = 'adquisiciones/ordencompra_delete.html'
    success_url = reverse_lazy('adquisiciones:ordencompra_listar')


class Reporte(View):

    def cabecera(self, pdf):
        #imagen = settings.MEDIA_ROOT+'\imagenes\conaf.jpg'
        #pdf.drawImage(imagen, 40, 520, 120, 90, preserveAspectRatio=True)
        pdf.setFont("Helvetica", 16)
        pdf.drawString(300, 550, u"ORDEN DE COMPRA")
        pdf.setFont("Helvetica", 10)
        #pdf.drawString(200, 770, u"")

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='application/pdf')
        #response['Content-Disposition']='attachment; filename="%s"'
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        self.cabecera(pdf)
        y = 600
        self.tabla(pdf, y)
        pdf.showPage()
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

    def tabla(self, pdf, y):
        contador = OrdenCompra.objects.values('departamento_id').count

        encabezados = ('N° Orden de Compra', 'Producto', 'total', 'estado', 'observacion', 'departamento', 'fecha')

        detalles = [(OrdenCompra.id, OrdenCompra.producto, OrdenCompra.total, OrdenCompra.estado, OrdenCompra.observacion, OrdenCompra.departamento, OrdenCompra.fecha)
                    for OrdenCompra in OrdenCompra.objects.all()]
        detalle_orden = Table([encabezados] + detalles, colWidths=[3 * cm, 5.5 * cm, 2 * cm, 1.2 * cm, 5 * cm, 3 * cm, 3 * cm])

        detalle_orden.setStyle(TableStyle(
            [
                ('ALIGN', (0, 0), (1, 0), 'CENTER'),
                ('GRID', (0, 0), (8, -1), 0.5, colors.darkgrey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('FONTSIZE', (0, 0), (-1, -1), 8)
                
            ]
        ))

        
        detalle_orden.wrapOn(pdf, 800, 600)
        detalle_orden.drawOn(pdf, 40, 450)
        pdf.setPageSize(landscape(letter))

    template_name = 'adquisiciones/reporte.html'
    #success_url = reverse_lazy('adquisiciones:ordencompra_listar')

class FacturaList(ListView):
    model = Factura
    template_name = 'adquisiciones/factura_list.html'


class FacturaCreate(CreateView):
    model = Factura
    form_class = FacturaForm
    template_name = 'adquisiciones/factura_create.html'
    success_url = reverse_lazy('adquisiciones:factura_listar')


class FacturaUpdate(UpdateView):
    model = Factura
    form_class = FacturaForm
    template_name = 'adquisiciones/factura_update.html'
    success_url = reverse_lazy('adquisiciones:factura_listar')


class FacturaDelete(DeleteView):
    model = Factura
    template_name = 'adquisiciones/factura_delete.html'
    success_url = reverse_lazy('adquisiciones:factura_listar')

trabajopython/adquisiciones/templates/adquisiciones/factura_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Factura-Registrar</title>
</head>
<body>
    {% extends 'adminlte/base.html'%}

    {%block content%}
    <div class="col-sm-12">
        <h1>REGISTRO DE FACTURAS</h1>
        <hr>
        <form method="POST" action="">
            {% csrf_token%}
            {{form.as_p}}
            <input type='submit' class="btn btn-primary" value='Guardar Registro'>
        </form>
    </div>
</body>
</html>
{%endblock%}

trabajopython/adquisiciones/templates/adquisiciones/factura_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | Factura-Eliminar</title>
  </head>
{% extends 'adminlte/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de factura?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'adquisiciones:factura_listar' %}">Cancelar</a>

</form>
</html>
{% endblock %}

trabajopython/adquisiciones/templates/adquisiciones/factura_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Listar Producto</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE FACTURAS</h1>
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Producto</td>
				<td>Proveedor</td>
				<td>Fecha</td>
				<td>Total</td>
			</tr>
		</thead>
		<tbody>
			{% for factura_list in object_list %}
			<tr>
				<td>{{factura_list.producto}}</td>
				<td>{{factura_list.proveedor}}</td>
				<td>{{factura_list.fecha}}</td>
				<td>{{factura_list.total}}</td>
        <td style="border :1px solid transparent ">
				<a class="btn btn-primary" href="{% url 'adquisiciones:factura_editar' factura_list.id %}"><i class="ion-edit"></i> Editar</a>
              	<a class="btn btn-danger" href="{% url 'adquisiciones:factura_eliminar' factura_list.id %}"> <i class="ion-android-delete"></i> Eliminar</a>
        </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay registros de productos</h1>
	<hr>
	<td>
		<a class="btn btn-primary" href="{% url 'adquisiciones:factura_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>
	</td>
	{% endif %}
</div>
</div>
 </html>
{% endblock %}

trabajopython/adquisiciones/templates/adquisiciones/factura_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | Factura-Editar</title>
  </head>
{% extends 'adminlte/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR FACTURA</h1>
          <hr>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
            </form>
      </div>
  </div>
  <br>
</html>
{%endblock%}

trabajopython/adquisiciones/templates/adquisiciones/ordencompra_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Orden de Compra-Registrar</title>
</head>
<body>
    {% extends 'adminlte/base.html'%}

    {%block content%}
    <div class="col-sm-12">
        <h1>REGISTRO DE ORDENES DE COMPRA</h1>
        <hr>
        <form method="POST" action="">
            {% csrf_token%}
            {{form.as_p}}
            <input type='submit' class="btn btn-primary" value='Guardar Registro'>
        </form>
    </div>
</body>
</html>
{%endblock%}

trabajopython/adquisiciones/templates/adquisiciones/ordencompra_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | Orden de Compra-Eliminar</title>
  </head>
{% extends 'adminlte/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de orden de compra?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'adquisiciones:ordencompra_listar' %}">Cancelar</a>

</form>
</html>
{% endblock %}

trabajopython/adquisiciones/templates/adquisiciones/ordencompra_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema | Listar Orden de Compra</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}

<div id="" class="gray-bg"><br>
	<a class="btn btn-primary" href="{% url 'adquisiciones:reporte' %}"> <i class="ion-ios-printer-outline"> </i> Generar Reporte</a>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE ORDENES DE COMPRA</h1>
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Producto</td>
				<td>Total</td>
				<td>Estado</td>
				<td>Observacion</td>
				<td>Departamento</td>
				<td>Fecha</td>
			</tr>
		</thead>
		<tbody>
			{% for ordencompra_list in object_list %}
			<tr>
				<td>{{ordencompra_list.producto}}</td>
				<td>{{ordencompra_list.total}}</td>
				<td>{{ordencompra_list.estado}}</td>
				<td>{{ordencompra_list.observacion}}</td>
				<td>{{ordencompra_list.departamento}}</td>
				<td>{{ordencompra_list.fecha}}</td>
        <td style="border :1px solid transparent ">
				<a class="btn btn-primary" href="{% url 'adquisiciones:ordencompra_editar' ordencompra_list.id %}"><i class="ion-edit"></i> Editar</a>
              	<a class="btn btn-danger" href="{% url 'adquisiciones:ordencompra_eliminar' ordencompra_list.id %}"> <i class="ion-android-delete"></i> Eliminar</a>
        </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay registros de ordenes de compra</h1>
	<hr>
	<td>
		<a class="btn btn-primary" href="{% url 'adquisiciones:ordencompra_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>
	</td>
	{% endif %}
</div>
</div>
 </html>
{% endblock %}

trabajopython/adquisiciones/templates/adquisiciones/ordencompra_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema | Orden de Compra-Editar</title>
  </head>
{% extends 'adminlte/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR ORDEN DE COMPRA</h1>
          <hr>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
            </form>
      </div>
  </div>
  <br>
</html>
{%endblock%}

trabajopython/adquisiciones/templates/adquisiciones/reporte.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Adquisiciones | Reportes</title>
</head>
{% extends 'adminlte/base.html' %}
{% block content %}
	<div class="form-group">
		<div class="row">
			<div class="col-lg-1">
				<a href="{% url 'Adquisiciones:reporte' %}" class="btn btn-info btn-block">
					<span class=""></span>
				</a>
			</div>
		</div>
	</div>
</html>
{% endblock %}